apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dco2.resourceName" (list . "server-config") }}
type: Opaque
stringData:
  {{ .Values.configFileName }}: |-
    github_app:
      {{- if .Values.server.config.githubApp.apiHost }}
      api_host: {{ .Values.server.config.githubApp.apiHost }}
      {{- end }}
      app_id: {{ .Values.server.config.githubApp.appId }}
      private_key: |-
{{ .Values.server.config.githubApp.privateKey | default "" | nindent 8 }}
      webhook_secret: {{ .Values.server.config.githubApp.webhookSecret | quote }}
    log_format: {{ .Values.server.config.logFormat }}
    server_addr: {{ .Values.server.config.addr }}
