apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    {{- include "dco2.labels" . | nindent 4 }}
  name: {{ include "dco2.resourceName" (list . "server") }}
spec:
  replicas: {{ .Values.server.deploy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      {{- include "dco2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        {{- include "dco2.selectorLabels" . | nindent 8 }}
      {{- with .Values.server.deploy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.deploy.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - command:
            - dco2-server
          args:
            - --config-file
            - {{ printf "%s/%s" .Values.configDir .Values.configFileName | quote }}
          image: {{ printf "%s:%s" .Values.server.deploy.image.repository (default "latest" .Values.imageTag) }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: server
          {{- with .Values.server.deploy.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          {{- with .Values.server.deploy.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.server.deploy.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.configDir | quote }}
              name: server-config
              readOnly: true
      volumes:
        - name: server-config
          secret:
            secretName: {{ include "dco2.resourceName" (list . "server-config") }}
