{{- if .Values.server.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/component: server
    {{- include "dco2.labels" . | nindent 4 }}
  name: {{ include "dco2.resourceName" (list . "server") }}
  {{- with .Values.server.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.ingress.className }}
  ingressClassName: {{ .Values.server.ingress.className }}
  {{- end }}
  defaultBackend:
    service:
      name: {{ include "dco2.resourceName" (list . "server") }}
      port:
        number: {{ .Values.server.ingress.backendServicePort }}
  {{- with .Values.server.ingress.hosts }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.server.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
